# Use a imagem oficial do Apache Airflow
FROM apache/airflow:2.5.1-python3.8

# Instale pacotes adicionais para conectar ao PostgreSQL e Kafka
USER root
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev

# Instale dependências do Python
USER airflow
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
