# Use uma imagem base de Spark com Hadoop e Kafka
FROM bitnami/spark:3.3.0

# Instale pacotes adicionais para Spark e Kafka
USER root
RUN apt-get update && apt-get install -y \
    openjdk-11-jdk-headless \
    netcat \
    curl

# Copie os scripts do Spark
USER root
COPY src/spark /opt/spark/work-dir
